    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Alberto Sánchez Macías" />
    <meta name="generator" content="NetBeans 19" />
    <meta name="copyright" content="DAW" />
    <meta name="robots" content="index, follow" />
    <meta name="keywords" content="Hibernate" />
    <meta name="description" content="Aplicación para crear tus propios eventos y compartirlo con los demás" />
