<footer class="bg-body-tertiary text-body-emphasis border-top py-4 mt-5">
  <div class="container d-flex flex-column flex-md-row justify-content-between align-items-center text-center text-md-start gap-3">

   <div>
      <p class="mb-0 fw-bold">&copy; 2025 Alberto S&aacute;nchez Mac&iacute;as - EntreHobbies</p>
    </div>

    <ul class="list-unstyled d-flex flex-column flex-md-row gap-3 mb-0">
      <li><a href="#" class="text-decoration-none text-body-emphasis">Sobre nosotros</a></li>
      <li><a href="#" class="text-decoration-none text-body-emphasis">Contacto</a></li>
      <li><a href="#" class="text-decoration-none text-body-emphasis">Privacidad</a></li>
    </ul>

    <div class="d-flex gap-3">
      <a href="https://www.instagram.com"
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Instagram">
        <i class="bi bi-instagram text-body-emphasis fs-5"></i>
      </a>
      <a href="https://www.twitter.com"
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Twitter">
        <i class="bi bi-twitter-x text-body-emphasis fs-5"></i>
      </a>
      <a href="https://www.linkedin.com"
        target="_blank"
        rel="noopener noreferrer"
        aria-label="LinkedIn">
        <i class="bi bi-linkedin text-body-emphasis fs-5"></i>
      </a>
    </div>

  </div>
</footer>
